name: (Load test) Build & Deploy SEA-Beta to Gov.UK PaaS

on:
  push:
    branches: [ loadtest ]

jobs:
  call-build-and-deploy-workflow:
    uses: ./.github/workflows/_build-and-deploy-to-gov-paas.yml
    with:
      environment_name: loadtest
    secrets:
      gov_paas_password: ${{ secrets.TEAM_BEISESASSUPPORT_GOV_PAAS_PASSWORD }}
